// Generated by tools/p5t.py gallery; do not edit by hand.
window.P5T_PLAYERS = [
 {
  "name": "list",
  "title": "List",
  "description": "Every sketch grouped by date; pick one to play it beside the list, or loop through them all. URL settings: loop, secs."
 },
 {
  "name": "wall",
  "title": "Wall",
  "description": "A grid of sketches in random order; every few seconds one cell gets the next sketch. URL settings: cols, rows, w, h, swap, zoom, labels, credit."
 }
];
