#!/usr/bin/env python3
"""Helpers for porting the #p5t Processing sketches to p5.js.

  python3 tools/p5t.py gallery      # rebuild p5js/index.html

Other scripts import write_sketch() to lay out a converted sketch as
p5js/<same path as in #p5t>/{index.html, sketch.js}.
"""

import html
import json
import sys
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "#p5t"
OUT = ROOT / "p5js"
P5_VERSION = "1.11.12"
P5_URL = f"https://cdnjs.cloudflare.com/ajax/libs/p5.js/{P5_VERSION}/p5.min.js"
UPSTREAM = "https://github.com/madparker/-p5t/blob/main/"

# Scratch copies left next to the real sketch; not ported.
SKIP_FILES = {"BAK.pde", "Temop.pde"}

INDEX_HTML = """<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
    <script src="{p5_url}"></script>
    <script src="sketch.js"></script>
    <style>
      body {{
        margin: 0;
        padding: 0;
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        background-color: #d0d0d0;
      }}
    </style>
  </head>
  <body></body>
</html>
"""


def sketch_dirs():
    """Folders under #p5t (relative, posix) that hold a sketch."""
    dirs = {p.parent.relative_to(SRC).as_posix() for p in SRC.rglob("*.pde")}
    return sorted(dirs)


def main_pde(rel):
    d = SRC / rel
    named = d / f"{d.name}.pde"
    if named.exists():
        return named
    return sorted(p for p in d.glob("*.pde") if p.name not in SKIP_FILES)[0]


def upstream_url(pde):
    return UPSTREAM + quote(pde.relative_to(ROOT).as_posix())


def write_sketch(rel, body):
    """Write p5js/<rel>/index.html and sketch.js (header + body + original)."""
    pde = main_pde(rel)
    src_rel = pde.relative_to(ROOT).as_posix()
    original = pde.read_text().rstrip()
    if "*/" in original:
        raise ValueError(f"{src_rel} contains */ and can't sit in a block comment")
    name = Path(rel).name
    header = (
        f"// {name} (p5.js {P5_VERSION} port of a #p5t Processing sketch)\n"
        f"// {upstream_url(pde)}\n"
        f"// {src_rel}\n"
    )
    footer = f"\n// ---- Original Processing source: {src_rel}\n/*\n{original}\n*/\n"
    out = OUT / rel
    out.mkdir(parents=True, exist_ok=True)
    (out / "sketch.js").write_text(header + "\n" + body.strip() + "\n" + footer)
    (out / "index.html").write_text(
        INDEX_HTML.format(title=html.escape(name), p5_url=P5_URL)
    )


def build_gallery():
    items = []
    for rel in sketch_dirs():
        items.append(
            {
                "path": rel,
                "name": Path(rel).name,
                "group": str(Path(rel).parent),
                "done": (OUT / rel / "sketch.js").exists(),
                "src": upstream_url(main_pde(rel)),
            }
        )
    done = sum(i["done"] for i in items)
    page = GALLERY.replace("__DATA__", json.dumps(items)).replace(
        "__P5__", P5_VERSION
    )
    (OUT / "index.html").write_text(page)
    print(f"gallery: {done}/{len(items)} sketches converted")


GALLERY = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>#p5t in p5.js</title>
<!-- Generated by tools/p5t.py gallery; do not edit by hand. -->
<style>
  :root {
    --bg: #f4f3ef; --panel: #ffffff; --ink: #1d1d1b; --muted: #7a776f;
    --line: #dedbd2; --accent: #d6336c; --sel: #fbe3ec;
  }
  @media (prefers-color-scheme: dark) {
    :root {
      --bg: #151514; --panel: #1f1e1c; --ink: #ecebe6; --muted: #8f8b82;
      --line: #33312d; --accent: #f06595; --sel: #3a2230;
    }
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; height: 100vh; display: grid; grid-template-columns: 300px 1fr;
    background: var(--bg); color: var(--ink);
    font: 14px/1.4 ui-sans-serif, system-ui, -apple-system, sans-serif;
  }
  nav { border-right: 1px solid var(--line); overflow-y: auto; background: var(--panel); }
  header { padding: 16px; border-bottom: 1px solid var(--line); position: sticky; top: 0; background: var(--panel); }
  h1 { margin: 0 0 4px; font-size: 18px; }
  .meta { color: var(--muted); font-size: 12px; }
  label { display: flex; gap: 6px; align-items: center; margin-top: 8px; font-size: 12px; color: var(--muted); }
  h2 { margin: 0; padding: 10px 16px 4px; font-size: 11px; font-weight: 600;
       letter-spacing: .06em; text-transform: uppercase; color: var(--muted); }
  a.item { display: flex; justify-content: space-between; padding: 5px 16px;
           color: var(--ink); text-decoration: none; }
  a.item:hover { background: var(--bg); }
  a.item.sel { background: var(--sel); color: var(--accent); font-weight: 600; }
  a.item.todo { color: var(--muted); pointer-events: none; }
  a.item.todo::after { content: "todo"; font-size: 11px; }
  body.hide-todo a.item.todo { display: none; }
  main { display: grid; grid-template-rows: auto 1fr; min-width: 0; }
  .bar { display: flex; gap: 16px; align-items: baseline; padding: 12px 16px;
         border-bottom: 1px solid var(--line); flex-wrap: wrap; }
  .bar strong { font-size: 16px; }
  .bar a { color: var(--accent); font-size: 13px; }
  .bar .path { color: var(--muted); font-size: 12px; font-family: ui-monospace, monospace; }
  iframe { width: 100%; height: 100%; border: 0; background: #d0d0d0; }
  .empty { display: grid; place-items: center; color: var(--muted); }
  @media (max-width: 700px) {
    body { grid-template-columns: 1fr; grid-template-rows: 40vh 1fr; height: auto; min-height: 100vh; }
    nav { border-right: 0; border-bottom: 1px solid var(--line); }
    iframe { height: 540px; }
  }
</style>
</head>
<body>
<nav>
  <header>
    <h1>#p5t in p5.js</h1>
    <div class="meta" id="count"></div>
    <label><input type="checkbox" id="hide" /> Hide unconverted</label>
  </header>
  <div id="list"></div>
</nav>
<main>
  <div class="bar" id="bar"><span class="meta">Pick a sketch</span></div>
  <div class="empty" id="view">Select a sketch from the list.</div>
</main>
<script>
const ITEMS = __DATA__;
const list = document.getElementById('list');
const done = ITEMS.filter(i => i.done).length;
document.getElementById('count').textContent =
  `${done} of ${ITEMS.length} converted · p5.js __P5__`;

let group = null;
for (const it of ITEMS) {
  if (it.group !== group) {
    group = it.group;
    const h = document.createElement('h2');
    h.textContent = group;
    list.append(h);
  }
  const a = document.createElement('a');
  a.className = 'item' + (it.done ? '' : ' todo');
  a.href = '#' + it.path;
  a.textContent = it.name;
  a.dataset.path = it.path;
  list.append(a);
}

const hide = document.getElementById('hide');
try { hide.checked = localStorage.getItem('hideTodo') === '1'; } catch (e) {}
const applyHide = () => {
  document.body.classList.toggle('hide-todo', hide.checked);
  try { localStorage.setItem('hideTodo', hide.checked ? '1' : '0'); } catch (e) {}
};
hide.addEventListener('change', applyHide);
applyHide();

function show() {
  const path = decodeURIComponent(location.hash.slice(1));
  const it = ITEMS.find(i => i.path === path && i.done);
  document.querySelectorAll('a.item').forEach(a =>
    a.classList.toggle('sel', a.dataset.path === path));
  if (!it) return;
  const url = path.split('/').map(encodeURIComponent).join('/') + '/';
  document.getElementById('bar').innerHTML = '';
  const bar = document.getElementById('bar');
  const title = document.createElement('strong');
  title.textContent = it.name;
  const p = document.createElement('span');
  p.className = 'path';
  p.textContent = path;
  const open = Object.assign(document.createElement('a'),
    { href: url, target: '_blank', textContent: 'Open ↗' });
  const code = Object.assign(document.createElement('a'),
    { href: url + 'sketch.js', target: '_blank', textContent: 'sketch.js' });
  const orig = Object.assign(document.createElement('a'),
    { href: it.src, target: '_blank', textContent: 'Original .pde' });
  bar.append(title, p, open, code, orig);
  const old = document.getElementById('view');
  const frame = document.createElement('iframe');
  frame.id = 'view';
  frame.src = url;
  old.replaceWith(frame);
}
window.addEventListener('hashchange', show);
show();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    if sys.argv[1:] == ["gallery"]:
        build_gallery()
    else:
        sys.exit(__doc__)
